const contries = [
    { val: 'af', name: 'Afghanistan' },
    { val: 'ax', name: 'Aland Islands' },
    { val: 'al', name: 'Albania' },
    { val: 'dz', name: 'Algeria' },
    { val: 'as', name: 'American Samoa' },
    { val: 'ad', name: 'Andorra' },
    { val: 'ao', name: 'Angola' },
    { val: 'ai', name: 'Anguilla' },
    { val: 'ag', name: 'Antigua' },
    { val: 'ar', name: 'Argentina' },
    { val: 'am', name: 'Armenia' },
    { val: 'aw', name: 'Aruba' },
    { val: 'au', name: 'Australia' },
    { val: 'at', name: 'Austria' },
    { val: 'az', name: 'Azerbaijan' },
    { val: 'bs', name: 'Bahamas' },
    { val: 'bh', name: 'Bahrain' },
    { val: 'bd', name: 'Bangladesh' },
    { val: 'bb', name: 'Barbados' },
    { val: 'by', name: 'Belarus' },
    { val: 'be', name: 'Belgium' },
    { val: 'bz', name: 'Belize' },
    { val: 'bj', name: 'Benin' },
    { val: 'bm', name: 'Bermuda' },
    { val: 'bt', name: 'Bhutan' },
    { val: 'bo', name: 'Bolivia' },
    { val: 'ba', name: 'Bosnia' },
    { val: 'bw', name: 'Botswana' },
    { val: 'bv', name: 'Bouvet Island' },
    { val: 'br', name: 'Brazil' },
    { val: 'vg', name: 'British Virgin Islands' },
    { val: 'bn', name: 'Brunei' },
    { val: 'bg', name: 'Bulgaria' },
    { val: 'bf', name: 'Burkina Faso' },
    { val: 'mm', name: 'Burma' },
    { val: 'bi', name: 'Burundi' },
    { val: 'tc', name: 'Caicos Islands' },
    { val: 'kh', name: 'Cambodia' },
    { val: 'cm', name: 'Cameroon' },
    { val: 'ca', name: 'Canada' },
    { val: 'cv', name: 'Cape Verde' },
    { val: 'ky', name: 'Cayman Islands' },
    { val: 'cf', name: 'Central African Republic' },
    { val: 'td', name: 'Chad' },
    { val: 'cl', name: 'Chile' },
    { val: 'cn', name: 'China' },
    { val: 'cx', name: 'Christmas Island' },
    { val: 'cc', name: 'Cocos Islands' },
    { val: 'co', name: 'Colombia' },
    { val: 'km', name: 'Comoros' },
    { val: 'cg', name: 'Congo Brazzaville' },
    { val: 'cd', name: 'Congo' },
    { val: 'ck', name: 'Cook Islands' },
    { val: 'cr', name: 'Costa Rica' },
    { val: 'ci', name: 'Cote Divoire' },
    { val: 'hr', name: 'Croatia' },
    { val: 'cu', name: 'Cuba' },
    { val: 'cy', name: 'Cyprus' },
    { val: 'cz', name: 'Czech Republic' },
    { val: 'dk', name: 'Denmark' },
    { val: 'dj', name: 'Djibouti' },
    { val: 'dm', name: 'Dominica' },
    { val: 'do', name: 'Dominican Republic' },
    { val: 'ec', name: 'Ecuador' },
    { val: 'eg', name: 'Egypt' },
    { val: 'sv', name: 'El Salvador' },
    { val: 'gb', name: 'England' },
    { val: 'gq', name: 'Equatorial Guinea' },
    { val: 'er', name: 'Eritrea' },
    { val: 'ee', name: 'Estonia' },
    { val: 'et', name: 'Ethiopia' },
    { val: 'eu', name: 'European Union' },
    { val: 'fk', name: 'Falkland Islands' },
    { val: 'fo', name: 'Faroe Islands' },
    { val: 'fj', name: 'Fiji' },
    { val: 'fi', name: 'Finland' },
    { val: 'fr', name: 'France' },
    { val: 'gf', name: 'French Guiana' },
    { val: 'pf', name: 'French Polynesia' },
    { val: 'tf', name: 'French Territories' },
    { val: 'ga', name: 'Gabon' },
    { val: 'gm', name: 'Gambia' },
    { val: 'ge', name: 'Georgia' },
    { val: 'de', name: 'Germany' },
    { val: 'gh', name: 'Ghana' },
    { val: 'gi', name: 'Gibraltar' },
    { val: 'gr', name: 'Greece' },
    { val: 'gl', name: 'Greenland' },
    { val: 'gd', name: 'Grenada' },
    { val: 'gp', name: 'Guadeloupe' },
    { val: 'gu', name: 'Guam' },
    { val: 'gt', name: 'Guatemala' },
    { val: 'gw', name: 'Guinea-Bissau' },
    { val: 'gn', name: 'Guinea' },
    { val: 'gy', name: 'Guyana' },
    { val: 'ht', name: 'Haiti' },
    { val: 'hm', name: 'Heard Island' },
    { val: 'hn', name: 'Honduras' },
    { val: 'hk', name: 'Hong Kong' },
    { val: 'hu', name: 'Hungary' },
    { val: 'is', name: 'Iceland' },
    { val: 'in', name: 'India' },
    { val: 'io', name: 'Indian Ocean Territory' },
    { val: 'id', name: 'Indonesia' },
    { val: 'ir', name: 'Iran' },
    { val: 'iq', name: 'Iraq' },
    { val: 'ie', name: 'Ireland' },
    { val: 'il', name: 'Israel' },
    { val: 'it', name: 'Italy' },
    { val: 'jm', name: 'Jamaica' },
    { val: 'jp', name: 'Japan' },
    { val: 'jo', name: 'Jordan' },
    { val: 'kz', name: 'Kazakhstan' },
    { val: 'ke', name: 'Kenya' },
    { val: 'ki', name: 'Kiribati' },
    { val: 'kw', name: 'Kuwait' },
    { val: 'kg', name: 'Kyrgyzstan' },
    { val: 'la', name: 'Laos' },
    { val: 'lv', name: 'Latvia' },
    { val: 'lb', name: 'Lebanon' },
    { val: 'ls', name: 'Lesotho' },
    { val: 'lr', name: 'Liberia' },
    { val: 'ly', name: 'Libya' },
    { val: 'li', name: 'Liechtenstein' },
    { val: 'lt', name: 'Lithuania' },
    { val: 'lu', name: 'Luxembourg' },
    { val: 'mo', name: 'Macau' },
    { val: 'mk', name: 'Macedonia' },
    { val: 'mg', name: 'Madagascar' },
    { val: 'mw', name: 'Malawi' },
    { val: 'my', name: 'Malaysia' },
    { val: 'mv', name: 'Maldives' },
    { val: 'ml', name: 'Mali' },
    { val: 'mt', name: 'Malta' },
    { val: 'mh', name: 'Marshall Islands' },
    { val: 'mq', name: 'Martinique' },
    { val: 'mr', name: 'Mauritania' },
    { val: 'mu', name: 'Mauritius' },
    { val: 'yt', name: 'Mayotte' },
    { val: 'mx', name: 'Mexico' },
    { val: 'fm', name: 'Micronesia' },
    { val: 'md', name: 'Moldova' },
    { val: 'mc', name: 'Monaco' },
    { val: 'mn', name: 'Mongolia' },
    { val: 'me', name: 'Montenegro' },
    { val: 'ms', name: 'Montserrat' },
    { val: 'ma', name: 'Morocco' },
    { val: 'mz', name: 'Mozambique' },
    { val: 'na', name: 'Namibia' },
    { val: 'nr', name: 'Nauru' },
    { val: 'np', name: 'Nepal' },
    { val: 'an', name: 'Netherlands Antilles' },
    { val: 'nl', name: 'Netherlands' },
    { val: 'nc', name: 'New Caledonia' },
    { val: 'pg', name: 'New Guinea' },
    { val: 'nz', name: 'New Zealand' },
    { val: 'ni', name: 'Nicaragua' },
    { val: 'ne', name: 'Niger' },
    { val: 'ng', name: 'Nigeria' },
    { val: 'nu', name: 'Niue' },
    { val: 'nf', name: 'Norfolk Island' },
    { val: 'kp', name: 'North Korea' },
    { val: 'mp', name: 'Northern Mariana Islands' },
    { val: 'no', name: 'Norway' },
    { val: 'om', name: 'Oman' },
    { val: 'pk', name: 'Pakistan' },
    { val: 'pw', name: 'Palau' },
    { val: 'ps', name: 'Palestine' },
    { val: 'pa', name: 'Panama' },
    { val: 'py', name: 'Paraguay' },
    { val: 'pe', name: 'Peru' },
    { val: 'ph', name: 'Philippines' },
    { val: 'pn', name: 'Pitcairn Islands' },
    { val: 'pl', name: 'Poland' },
    { val: 'pt', name: 'Portugal' },
    { val: 'pr', name: 'Puerto Rico' },
    { val: 'qa', name: 'Qatar' },
    { val: 're', name: 'Reunion' },
    { val: 'ro', name: 'Romania' },
    { val: 'ru', name: 'Russia' },
    { val: 'rw', name: 'Rwanda' },
    { val: 'sh', name: 'Saint Helena' },
    { val: 'kn', name: 'Saint Kitts and Nevis' },
    { val: 'lc', name: 'Saint Lucia' },
    { val: 'pm', name: 'Saint Pierre' },
    { val: 'vc', name: 'Saint Vincent' },
    { val: 'ws', name: 'Samoa' },
    { val: 'sm', name: 'San Marino' },
    { val: 'gs', name: 'Sandwich Islands' },
    { val: 'st', name: 'Sao Tome' },
    { val: 'sa', name: 'Saudi Arabia' },
    { val: 'sn', name: 'Senegal' },
    { val: 'cs', name: 'Serbia' },
    { val: 'rs', name: 'Serbia' },
    { val: 'sc', name: 'Seychelles' },
    { val: 'sl', name: 'Sierra Leone' },
    { val: 'sg', name: 'Singapore' },
    { val: 'sk', name: 'Slovakia' },
    { val: 'si', name: 'Slovenia' },
    { val: 'sb', name: 'Solomon Islands' },
    { val: 'so', name: 'Somalia' },
    { val: 'za', name: 'South Africa' },
    { val: 'kr', name: 'South Korea' },
    { val: 'es', name: 'Spain' },
    { val: 'lk', name: 'Sri Lanka' },
    { val: 'sd', name: 'Sudan' },
    { val: 'sr', name: 'Suriname' },
    { val: 'sj', name: 'Svalbard' },
    { val: 'sz', name: 'Swaziland' },
    { val: 'se', name: 'Sweden' },
    { val: 'ch', name: 'Switzerland' },
    { val: 'sy', name: 'Syria' },
    { val: 'tw', name: 'Taiwan' },
    { val: 'tj', name: 'Tajikistan' },
    { val: 'tz', name: 'Tanzania' },
    { val: 'th', name: 'Thailand' },
    { val: 'tl', name: 'Timorleste' },
    { val: 'tg', name: 'Togo' },
    { val: 'tk', name: 'Tokelau' },
    { val: 'to', name: 'Tonga' },
    { val: 'tt', name: 'Trinidad' },
    { val: 'tn', name: 'Tunisia' },
    { val: 'tr', name: 'Turkey' },
    { val: 'tm', name: 'Turkmenistan' },
    { val: 'tv', name: 'Tuvalu' },
    { val: 'ug', name: 'Uganda' },
    { val: 'ua', name: 'Ukraine' },
    { val: 'ae', name: 'United Arab Emirates' },
    { val: 'us', name: 'United States' },
    { val: 'uy', name: 'Uruguay' },
    { val: 'um', name: 'Us Minor Islands' },
    { val: 'vi', name: 'Us Virgin Islands' },
    { val: 'uz', name: 'Uzbekistan' },
    { val: 'vu', name: 'Vanuatu' },
    { val: 'va', name: 'Vatican City' },
    { val: 've', name: 'Venezuela' },
    { val: 'vn', name: 'Vietnam' },
    { val: 'wf', name: 'Wallis and Futuna' },
    { val: 'eh', name: 'Western Sahara' },
    { val: 'ye', name: 'Yemen' },
    { val: 'zm', name: 'Zambia' },
    { val: 'zw', name: 'Zimbabwe' },
];

export default contries;
